#############################################################################################################
#
#   ОБЩИЕ СВЕДЕНИЯ ОБ ЭТОМ ФАЙЛЕ КОНФИГУРАЦИИ
#
#############################################################################################################

# Версия схемы конфигурации (версия класса AwdServerConfig), для которой предназначен этот файл.
schemaVersion: 1




#############################################################################################################
#
#   ПУЛ ПОТОКОВ
#
#############################################################################################################

# Максимальное количество заданий (тасков) в очереди на выполнение в пуле потоков.
executorQueueCapacity: 1000

# Максимальное количество активных потоков в пуле потоков. Также см. {udpMaxVirtualConnections}.
executorMaxThreads: 100

# Максимальное время существования бездействующего потока в пуле потоков.
executorThreadsKeepAliveSeconds: 60 # 1 минута




#############################################################################################################
#
#   UDP-СЕРВЕР
#
#############################################################################################################

# Порт, по которому и принимаются, и отправляются данные.
udpServerPort: 23132

# Размер буффера приёмника в байтах (максимальный размер сообщения, которое можно принять за раз целиком).
udpServerBufferSize: 1200

# Максимальное количество активных виртуальных соединений. Должно быть МЕНЬШЕ, чем {executorMaxThreads}.
udpMaxVirtualConnections: 50




#############################################################################################################
#
#   ЧИСТИЛЬЩИКИ (БАЗЫ ДАННЫХ, ПАМЯТИ, ...)
#
#############################################################################################################

# Максимальное время жизни бездействующих игровых комнат.
cleanerLobbiesMaxIdleMillis: 1200000 # 20 минут

# Периодичность чистки игровых комнат.
cleanerLobbiesCleanupPeriodMillis: 600000 # 10 минут

# Максимальное время жизни бездействующих виртуальных соединений.
cleanerVirConsMaxIdleMillis: 5000 # 5 секунд

# Периодичность чистки виртуальных соединений.
cleanerVirConsCleanupPeriodMillis: 2500 # 2.5 секунды




#############################################################################################################
#
#   ИГРА
#
#############################################################################################################

# Число игровых тиков (обновлений) в секунду.
gameTps: 25

# Максимальное количество игроков в игровой комнате.
maxLobbySize: 4

# Частота отправки пакетов Ping всем активным клиентам, НЕ находящимся в игре (НЕ PLAY), в тиках.
# Вне игры пингуем часто, чтобы можно было уверенно пользоваться системой "важных" (important) пакетов.
nonplayPingPeriodTicks: 2

# Частота отправки пакетов Ping всем активным клиентам, находящимся в игре (PLAY), в тиках.
# Во время игры пингуем редко, т.к. сервер и игроки и так часто обмениваются пакетами состояния игры.
playPingPeriodTicks: 25

# Минимальное количество игроков в комнате, необходимое для начала игры.
minPlayersToStart: 1
