#############################################################################################################
#
#   ОБЩИЕ СВЕДЕНИЯ ОБ ЭТОМ ФАЙЛЕ КОНФИГУРАЦИИ
#
#############################################################################################################

# Версия схемы конфигурации (версия класса AwdServerConfig), для которой предназначен этот файл.
schemaVersion: 1




#############################################################################################################
#
#   ПУЛ ПОТОКОВ
#
#############################################################################################################

# Максимальное количество заданий (тасков) в очереди на выполнение в пуле потоков.
executorQueueCapacity: 1000

# Максимальное количество активных потоков в пуле потоков.
executorMaxThreads: 100

# Максимальное время существования бездействующего потока в пуле потоков.
executorThreadsKeepAliveSeconds: 60 # 1 минута




#############################################################################################################
#
#   UDP-СЕРВЕР
#
#############################################################################################################

# Порт, по которому и принимаются, и отправляются данные.
udpServerPort: 23132

# Размер буффера приёмника в байтах (максимальный размер сообщения, которое можно принять за раз целиком).
udpServerBufferSize: 51200

# Максимальное время жизни бездействующих игровых комнат.
dbCleanerLobbiesMaxObjectLifespanMillis: 1200000 # 20 минут

# Периодичность чистки игровых комнат.
dbCleanerLobbiesCleanupPeriodMillis: 600000 # 10 минут

# Максимальное время жизни бездействующих виртуальных соединений.
dbCleanerVirtualConnectionsMaxObjectLifespanMillis: 240000 # 4 минуты

# Периодичность чистки виртуальных соединений.
dbCleanerVirtualConnectionsCleanupPeriodMillis: 120000 # 2 минуты
