#############################################################################################################
#
#   ОБЩИЕ СВЕДЕНИЯ ОБ ЭТОМ ФАЙЛЕ КОНФИГУРАЦИИ
#
#############################################################################################################

# Версия схемы конфигурации (версия класса AwdServerConfig), для которой предназначен этот файл.
schemaVersion: 1




#############################################################################################################
#
#   ПУЛ ПОТОКОВ
#
#############################################################################################################

# Максимальное количество заданий (тасков) в очереди на выполнение в пуле потоков.
executorQueueCapacity: 1000

# Максимальное количество активных потоков в пуле потоков.
executorMaxThreads: 100

# Максимальное время существования бездействующего потока в пуле потоков.
executorThreadsKeepAliveSeconds: 60 # 1 минута




#############################################################################################################
#
#   UDP-СЕРВЕР
#
#############################################################################################################

# Порт, по которому и принимаются, и отправляются данные.
udpServerPort: 23132

# Размер буффера приёмника в байтах (максимальный размер сообщения, которое можно принять за раз целиком).
udpServerBufferSize: 1024




#############################################################################################################
#
#   ЧИСТИЛЬЩИКИ (БАЗЫ ДАННЫХ, ПАМЯТИ, ...)
#
#############################################################################################################

# Максимальное время жизни бездействующих игровых комнат.
cleanerLobbiesMaxIdleMillis: 1200000 # 20 минут

# Периодичность чистки игровых комнат.
cleanerLobbiesCleanupPeriodMillis: 600000 # 10 минут

# Максимальное время жизни бездействующих виртуальных соединений.
cleanerVirConsMaxIdleMillis: 60000 # 1 минута

# Периодичность чистки виртуальных соединений.
cleanerVirConsCleanupPeriodMillis: 15000 # 15 секунд




#############################################################################################################
#
#   ИГРА
#
#############################################################################################################

# Максимальное количество игроков в игровой комнате.
maxLobbySize: 4

# Частота отправки пакетов Ping всем активным клиентам (для поддержания виртуального соединения).
pingPeriodMillis: 1000
